### ISSUE TITLE
2019 Driver Station

### ISSUE THREAD

**Issue by vectorcrumb** [FRC-Utilities/LibDS-C#10]
Hi! I just wanted to ask if this library is working with 2019 robots. I understand that the creator of the project doesn't have access to an FRC robot right now, so is there any quick/easy way to test it the library? Thanks for the awesome project!

**Comment by alex-spataru** [comment]
Unfortunately, the LibDS does not work with 2019 robots (and neither with 2018 robots :disappointed:) because there are no devs actively working on these projects. You can find more information about this in this [QDriverStation issue thread](https://github.com/FRC-Utilities/QDriverStation/issues/58). If you want to test the library, you may try to use the FRC Simulator, using the QDriverStation (or any other project that uses LibDS) and setting the robot IP to `127.0.0.1`. At least that was the way I got 2014 robots to work with LibDS.

Greetings from Mexico!

**Comment by Teityan** [comment]
I want to proceed with the development of LibDS.
I using WireShark. How should we proceed with development?
Is it possible to decode the packet?

**Comment by Teityan** [comment]
QDrivarStation corrected with FRC roboRIO_2019_v14 worked, but the joystick button assignment seems to be wrong.
Also, the port changed from time to time and sometimes worked in 2015 and 2014.

**Comment by sagarreddypatil** [comment]
> Unfortunately, the LibDS does not work with 2019 robots (and neither with 2018 robots 😞) because there are no devs actively working on these projects. You can find more information about this in this [QDriverStation issue thread](https://github.com/FRC-Utilities/QDriverStation/issues/58). If you want to test the library, you may try to use the FRC Simulator, using the QDriverStation (or any other project that uses LibDS) and setting the robot IP to `127.0.0.1`. At least that was the way I got 2014 robots to work with LibDS.
> 
> Greetings from Mexico!

Hi, I am trying to get Driver Station working on MacOS(but parallels or bootcamp is not an option, as the macbooks are school provided), with the 2020 RoboRIO firmware. How do I do this? Could you elaborate on the method described here?

**Comment by Teityan** [comment]
This repository is only the communication portion of the DriverStation.
DriverStation is here.
https://github.com/FRC-Utilities/QDriverStation
QT must be installed on your computer before it can work.
https://www.qt.io/
Clone and build the Driverstation repository.
When I built it (On Windows 10), SDL was the 32bit version, causing compilation errors so I downloaded the 64bit version from the net and replaced it with a successful build.

**Comment by Teityan** [comment]
When tested with the 2019 version, the controller did not function properly.
The key you pressed and the key sent to the robot was different.
I will test the 2020 version when I have time.
I want to continue developing this application.

**Comment by Macnolo0x7D4** [comment]
Stay informed, I am making an alternative to LibDS. This will have the most current protocols supports. It's just a matter of waiting, I am doing reverse engineering to the protocols yet. I'll be posting it on reddit when I'm done.

**Comment by abrightwell** [comment]
@mcn2004 - Would you please post a link here to the relevant reddit post once such a post is started/available? As well, if you'd be willing to detail your 'process' for backwards engineering the protocol, then I'm sure some of us would be willing to help in that effort.

**Comment by Macnolo0x7D4** [comment]
Yes, I will. However, it will be in r/FRC.
