### ISSUE TITLE
Compilation process not documented.

### ISSUE THREAD

**Issue by Redrield** [FRC-Utilities/LibDS-C#2]
The README should include instructions for how to compile this library, as there may be people unfamiliar with how to compile Qt projects, and who can't figure it out because of the lack of a configure script. Simply telling people to run `qtmake`, `make`, and optionally `sudo make install` would help in this regard.

**Comment by alex-spataru** [comment]
Sorry for the late reply, I will update the README.md file in a moment.

**Comment by Redrield** [comment]
@alex-spataru See #3, I added installation to /usr/local/{lib, include} and added documentation to the README

**Comment by alex-spataru** [comment]
Merged, thanks!
