### ISSUE TITLE
LibDS on Robot?

### ISSUE THREAD

**Issue by BearzRobotics** [FRC-Utilities/LibDS-C#4]
How hard would it be to rework the library wear it can also be used on a robot (in this case a Rasp PI) to be able to send packets and communicate with Qdriverstation. That way there is only one implementation of its supported protocols for Qdriverstation. Then any new protocol add to the core other robot project will be able to make use of.

**Comment by 770352** [comment]
If you are talking about adding this to a competition setup, Its illegal. The only system that is allowed to interface with your robot on the field is the FRC Driver Station. You also can't enable your robot on the field at all unless in certain circumstances (You will more than likely be notified if you can enable on the field and probably be asked to teather up.

**Comment by BearzRobotics** [comment]
I'm talking about off-season hobby stuff. Hence, in this case a raspberry pi. To help grow the community and make it useful for tinkers to mess with that necessarily don't even have an interest  in first.

**Comment by 770352** [comment]
LibDS is a one way street. You can control a roborio, Not a Raspberry pi

**Comment by BearzRobotics** [comment]
Your not getting what I'm saying at all. I posted this in a time the
project was dying as a way to get interest in it from more than frc. Libds
implements the protocals for the qdriverstation to communicate on, my
question was if it would be possible to repurpose it to also been used on
the robot end so there is only one implantation of it. For example a
raspberry pi. This was a question asked again when the project was in
almost a completely dead state trying to spark interest in the driver
station again from a broader tinker's community.

**Comment by abrightwell** [comment]
I get what you are saying. I'm not sure what the level of effort would be to adapt it to a more 'generic' use case, but it is something that I've considered in the past for the exact purpose you're describing. Though, candidly, I feel like a more efficient/extensible/maintainable/open protocol would be desired. But, one of the most frustrating things about the current protocol, for me, is a lack of public documentation and specifications for it (granted I understand why FIRST and/or NI doesn't release it). So, this makes updating/maintaining it as it changes over the years more of a hassle than it is worth, IMHO. But that's just my gripe. Over all, I think the idea is a valid one and worth exploring if there were interest.
