### ISSUE TITLE
Will we see an update to 2018 protocol?

### ISSUE THREAD

**Issue by tjquillan** [FRC-Utilities/LibDS-C#5]
Will we see an update to the 2018 protocol or are the changes not substantial enough to warrent it?

**Comment by alex-spataru** [comment]
I don't know. Unfortunately, I am not in a FRC team anymore, so I cannot test changes in LibDS with a real robot or even a simulated one (e.g. using the FRC simulator that comes with LabVIEW).

AFAIK, the communication protocol should not have changed in 2018, so you should be able to control your robot without any issues.
